# Generated by Django 4.2.4 on 2023-08-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="box",
            name="breadth",
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name="box",
            name="height",
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name="box",
            name="length",
            field=models.IntegerField(max_length=10),
        ),
    ]
