# Generated by Django 4.2.4 on 2023-08-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_box_breadth_alter_box_height_alter_box_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="box",
            name="breadth",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="box",
            name="height",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="box",
            name="length",
            field=models.IntegerField(),
        ),
    ]
